// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/proto/EventService.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *duration.Duration     `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotifyBefore  *duration.Duration     `protobuf:"bytes,7,opt,name=notify_before,json=notifyBefore,proto3" json:"notify_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetNotifyBefore() *duration.Duration {
	if x != nil {
		return x.NotifyBefore
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_proto_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_api_proto_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{4}
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_api_proto_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDayRequest) Reset() {
	*x = ListDayRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDayRequest) ProtoMessage() {}

func (x *ListDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDayRequest.ProtoReflect.Descriptor instead.
func (*ListDayRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *ListDayRequest) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type ListWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWeekRequest) Reset() {
	*x = ListWeekRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWeekRequest) ProtoMessage() {}

func (x *ListWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWeekRequest.ProtoReflect.Descriptor instead.
func (*ListWeekRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *ListWeekRequest) GetStart() *timestamp.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type ListMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMonthRequest) Reset() {
	*x = ListMonthRequest{}
	mi := &file_api_proto_EventService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMonthRequest) ProtoMessage() {}

func (x *ListMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMonthRequest.ProtoReflect.Descriptor instead.
func (*ListMonthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{9}
}

func (x *ListMonthRequest) GetStart() *timestamp.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_api_proto_EventService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_EventService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_EventService_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_proto_EventService_proto protoreflect.FileDescriptor

const file_api_proto_EventService_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/EventService.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x9a\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12>\n" +
	"\rnotify_before\x18\a \x01(\v2\x19.google.protobuf.DurationR\fnotifyBefore\";\n" +
	"\x12CreateEventRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"<\n" +
	"\x13CreateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEventResponse\";\n" +
	"\x12UpdateEventRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"<\n" +
	"\x13UpdateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"@\n" +
	"\x0eListDayRequest\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"C\n" +
	"\x0fListWeekRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\"D\n" +
	"\x10ListMonthRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\"=\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events2\xc4\x03\n" +
	"\x0fCalendarService\x12J\n" +
	"\vCreateEvent\x12\x1c.calendar.CreateEventRequest\x1a\x1d.calendar.CreateEventResponse\x12J\n" +
	"\vDeleteEvent\x12\x1c.calendar.DeleteEventRequest\x1a\x1d.calendar.DeleteEventResponse\x12J\n" +
	"\vUpdateEvent\x12\x1c.calendar.UpdateEventRequest\x1a\x1d.calendar.UpdateEventResponse\x12A\n" +
	"\aListDay\x12\x18.calendar.ListDayRequest\x1a\x1c.calendar.ListEventsResponse\x12C\n" +
	"\bListWeek\x12\x19.calendar.ListWeekRequest\x1a\x1c.calendar.ListEventsResponse\x12E\n" +
	"\tListMonth\x12\x1a.calendar.ListMonthRequest\x1a\x1c.calendar.ListEventsResponseB\vZ\tapi/protob\x06proto3"

var (
	file_api_proto_EventService_proto_rawDescOnce sync.Once
	file_api_proto_EventService_proto_rawDescData []byte
)

func file_api_proto_EventService_proto_rawDescGZIP() []byte {
	file_api_proto_EventService_proto_rawDescOnce.Do(func() {
		file_api_proto_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_EventService_proto_rawDesc), len(file_api_proto_EventService_proto_rawDesc)))
	})
	return file_api_proto_EventService_proto_rawDescData
}

var file_api_proto_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_EventService_proto_goTypes = []any{
	(*Event)(nil),               // 0: calendar.Event
	(*CreateEventRequest)(nil),  // 1: calendar.CreateEventRequest
	(*CreateEventResponse)(nil), // 2: calendar.CreateEventResponse
	(*DeleteEventRequest)(nil),  // 3: calendar.DeleteEventRequest
	(*DeleteEventResponse)(nil), // 4: calendar.DeleteEventResponse
	(*UpdateEventRequest)(nil),  // 5: calendar.UpdateEventRequest
	(*UpdateEventResponse)(nil), // 6: calendar.UpdateEventResponse
	(*ListDayRequest)(nil),      // 7: calendar.ListDayRequest
	(*ListWeekRequest)(nil),     // 8: calendar.ListWeekRequest
	(*ListMonthRequest)(nil),    // 9: calendar.ListMonthRequest
	(*ListEventsResponse)(nil),  // 10: calendar.ListEventsResponse
	(*timestamp.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*duration.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_api_proto_EventService_proto_depIdxs = []int32{
	11, // 0: calendar.Event.start_time:type_name -> google.protobuf.Timestamp
	12, // 1: calendar.Event.duration:type_name -> google.protobuf.Duration
	12, // 2: calendar.Event.notify_before:type_name -> google.protobuf.Duration
	0,  // 3: calendar.CreateEventRequest.event:type_name -> calendar.Event
	0,  // 4: calendar.CreateEventResponse.event:type_name -> calendar.Event
	0,  // 5: calendar.UpdateEventRequest.event:type_name -> calendar.Event
	0,  // 6: calendar.UpdateEventResponse.event:type_name -> calendar.Event
	11, // 7: calendar.ListDayRequest.date:type_name -> google.protobuf.Timestamp
	11, // 8: calendar.ListWeekRequest.start:type_name -> google.protobuf.Timestamp
	11, // 9: calendar.ListMonthRequest.start:type_name -> google.protobuf.Timestamp
	0,  // 10: calendar.ListEventsResponse.events:type_name -> calendar.Event
	1,  // 11: calendar.CalendarService.CreateEvent:input_type -> calendar.CreateEventRequest
	3,  // 12: calendar.CalendarService.DeleteEvent:input_type -> calendar.DeleteEventRequest
	5,  // 13: calendar.CalendarService.UpdateEvent:input_type -> calendar.UpdateEventRequest
	7,  // 14: calendar.CalendarService.ListDay:input_type -> calendar.ListDayRequest
	8,  // 15: calendar.CalendarService.ListWeek:input_type -> calendar.ListWeekRequest
	9,  // 16: calendar.CalendarService.ListMonth:input_type -> calendar.ListMonthRequest
	2,  // 17: calendar.CalendarService.CreateEvent:output_type -> calendar.CreateEventResponse
	4,  // 18: calendar.CalendarService.DeleteEvent:output_type -> calendar.DeleteEventResponse
	6,  // 19: calendar.CalendarService.UpdateEvent:output_type -> calendar.UpdateEventResponse
	10, // 20: calendar.CalendarService.ListDay:output_type -> calendar.ListEventsResponse
	10, // 21: calendar.CalendarService.ListWeek:output_type -> calendar.ListEventsResponse
	10, // 22: calendar.CalendarService.ListMonth:output_type -> calendar.ListEventsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_EventService_proto_init() }
func file_api_proto_EventService_proto_init() {
	if File_api_proto_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_EventService_proto_rawDesc), len(file_api_proto_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_EventService_proto_goTypes,
		DependencyIndexes: file_api_proto_EventService_proto_depIdxs,
		MessageInfos:      file_api_proto_EventService_proto_msgTypes,
	}.Build()
	File_api_proto_EventService_proto = out.File
	file_api_proto_EventService_proto_goTypes = nil
	file_api_proto_EventService_proto_depIdxs = nil
}
